### ISSUE TITLE
前端传参为list，导致salt-api调用时，master执行无法解析

### ISSUE THREAD

**Issue by vekergu** [yueyongyue/saltshaker_api#5]
API接口：/saltshaker/api/v1.0/execute/shell
执行命令：  echo ok
调用类：ExecuteShell 中 minion_id = args["minion_id"]  ，前端传入minion_id是list导致salt-api调用时，master执行无法解析。
如果将这个参数解析 minion_id = ",".join(minion_id) 成字符串，命令执行成功，但是页面展示结果会出现异常：
总数： 12
成功： 1
失败： 11
失败主机： 1,.,6,3,2,8,9

**Comment by yueyongyue** [comment]
@vekergu 传递过来的值是个list 如下, shell_remote_execution方法是支持传递list的 
shell_remote_execution(["master", "127.0.0.1"], "echo true")

**Comment by yueyongyue** [comment]
salt 2019.2.0 client 传递参数发生改变
https://docs.saltstack.com/en/latest/ref/clients/index.html#client-interfaces
Changed in version 2017.7.0: Renamed from expr_form to tgt_type
